#ifndef EI_HTTP_DOCS_H
#define EI_HTTP_DOCS_H

#ifdef EI_GEMMA2
#define EI_DOC_MODEL "embeddinggemma-2"
#define EI_DOC_PORT "42667"
#else
#define EI_DOC_MODEL "embeddinggemma-300m"
#define EI_DOC_PORT "42666"
#endif

static const char EI_ROOT_JSON[] =
    "{\"name\":\"embeddinggemma\",\"status\":\"ok\","
    "\"docs\":\"/docs\",\"openapi\":\"/openapi.json\","
    "\"health\":\"/healthz\",\"routes\":["
    "\"GET /api/tags\",\"POST /api/embed\","
    "\"POST /v1/embeddings\"]}\n";

static const char EI_HEALTH_JSON[] = "{\"status\":\"ok\"}\n";

static const char EI_DOCS_HTML[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>embeddinggemma API</title>\n"
    "<style>\n"
    ":root{color-scheme:light dark;--bg:#f7f7f5;--surface:#fff;--text:#18181b;"
    "--muted:#5f6368;--line:#d9d9d4;--link:#075985;--get:#166534;--post:#9a3412;"
    "--code:#f0f0ec}*{box-sizing:border-box}body{margin:0;background:var(--bg);"
    "color:var(--text);font:15px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"
    "\"Segoe UI\",sans-serif;letter-spacing:0}header{background:var(--surface);"
    "border-bottom:1px solid var(--line)}.wrap{width:min(920px,calc(100% - 32px));"
    "margin:auto}header .wrap{padding:40px 0 30px}.eyebrow{margin:0 0 6px;"
    "font:700 12px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted)}"
    "h1{margin:0;font-size:32px;line-height:1.2;letter-spacing:0}header p{max-width:680px;"
    "margin:12px 0 0;color:var(--muted)}nav{display:flex;gap:18px;margin-top:20px}"
    "a{color:var(--link)}main{padding:8px 0 48px}section{padding:28px 0;"
    "border-bottom:1px solid var(--line)}section:last-child{border-bottom:0}"
    "h2{display:flex;align-items:center;gap:10px;margin:0 0 14px;font-size:20px;"
    "letter-spacing:0}.method{display:inline-block;padding:2px 7px;border:1px solid;"
    "border-radius:4px;font:700 12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}"
    ".get{color:var(--get)}.post{color:var(--post)}code,pre{font-family:"
    "ui-monospace,SFMono-Regular,Menlo,monospace}code{background:var(--code);"
    "padding:2px 4px;border-radius:3px}pre{overflow:auto;margin:14px 0 0;padding:16px;"
    "background:#202124;color:#f8f8f2;border-radius:6px;font-size:13px;line-height:1.5}"
    "table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:9px 10px;"
    "border:1px solid var(--line);text-align:left;vertical-align:top}th{background:"
    "var(--surface)}@media(prefers-color-scheme:dark){:root{--bg:#141414;"
    "--surface:#1d1d1d;--text:#f4f4f5;--muted:#a1a1aa;--line:#3f3f46;"
    "--link:#7dd3fc;--get:#86efac;--post:#fdba74;--code:#292929}}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header><div class=\"wrap\"><p class=\"eyebrow\">LOCAL EMBEDDING INFERENCE</p>"
    "<h1>embeddinggemma API</h1><p>HTTP interface for EmbeddingGemma with 768, 512, "
    "256, and 128-dimensional Matryoshka outputs.</p><nav>"
    "<a href=\"/openapi.json\">OpenAPI JSON</a><a href=\"/healthz\">Health</a>"
    "</nav></div></header>\n"
    "<main class=\"wrap\">\n"
    "<section><h2><span class=\"method get\">GET</span><code>/healthz</code></h2>"
    "<p>Returns HTTP 200 after the model and inference workspace are ready.</p>"
    "<pre>{\"status\":\"ok\"}</pre></section>\n"
    "<section><h2><span class=\"method get\">GET</span><code>/api/tags</code></h2>"
    "<p>Lists the model exposed by this server.</p>"
    "<pre>{\"models\":[{\"name\":\"" EI_DOC_MODEL "\"}]}</pre></section>\n"
    "<section><h2><span class=\"method post\">POST</span><code>/api/embed</code></h2>"
    "<p>Embeds one string or an array of strings. Text is processed exactly as "
    "provided; include the EmbeddingGemma prompt prefix for your task, such as "
    "<code>task: search result | query: {text}</code> for search queries and "
    "<code>title: none | text: {text}</code> for documents.</p>"
    "<table><thead><tr><th>Field</th><th>Type</th><th>Contract</th></tr>"
    "</thead><tbody><tr><td><code>input</code></td><td>string or string[]</td>"
    "<td>Required; array limit defaults to 32</td></tr><tr><td><code>model</code></td>"
    "<td>string</td><td>Optional compatibility field</td></tr><tr>"
    "<td><code>dimensions</code></td><td>integer</td><td>768, 512, 256, or 128; "
    "default 768</td></tr><tr><td><code>encoding_format</code></td><td>string</td>"
    "<td><code>float</code> or <code>base64</code>; default float</td></tr>"
    "</tbody></table><pre>curl -sS http://127.0.0.1:" EI_DOC_PORT "/api/embed \\\n"
    "  -H 'Content-Type: application/json' \\\n"
    "  -d '{\"input\":[\"task: search result | query: what powers the cell\"],"
    "\"dimensions\":256}'</pre><pre>{\"embeddings\":[[0.0123, -0.0456, ...]]}</pre>"
    "</section>\n"
    "<section><h2><span class=\"method post\">POST</span>"
    "<code>/v1/embeddings</code></h2>"
    "<p>OpenAI-compatible embeddings endpoint. It accepts the same inputs, "
    "dimensions, and encoding formats as <code>/api/embed</code>, requires a "
    "model name, and returns the OpenAI list envelope with per-item indexes "
    "and tokenizer usage.</p>"
    "<pre>curl -sS http://127.0.0.1:" EI_DOC_PORT "/v1/embeddings \\\n"
    "  -H 'Content-Type: application/json' \\\n"
    "  -d '{\"model\":\"" EI_DOC_MODEL "\",\"input\":["
    "\"task: search result | query: what powers the cell\"]}'</pre>"
    "<pre>{\"object\":\"list\",\"data\":[{\"object\":\"embedding\","
    "\"embedding\":[0.0123, -0.0456, ...],\"index\":0}],"
    "\"model\":\"" EI_DOC_MODEL "\",\"usage\":{\"prompt_tokens\":10,"
    "\"total_tokens\":10}}</pre></section>\n"
#ifdef EI_GEMMA2
    "<section><h2>Images, audio, video and mixed inputs</h2>"
    "<p>Both embedding routes accept an input object with ordered content parts, "
    "or an array of these objects. Text parts contain a text string; image, audio "
    "and video parts contain base64 bytes in data. A video part can set fps "
    "(default 1, maximum 30). Include model for the OpenAI route.</p>"
    "<pre>{\"input\":{\"content\":[{\"type\":\"text\",\"text\":\"A red square\"},"
    "{\"type\":\"image\",\"data\":\"BASE64_BYTES\"}]},\"dimensions\":256}</pre>"
    "<p>Inputs are limited to 64 parts, 8192 tokens, 32 sampled video frames, "
    "16 megapixels per image/frame, 327.68 seconds per audio part, and 128 MiB "
    "of decoded input/frame buffers. The HTTP body limit is 16 MiB. "
    "Requests for an unloaded encoder are rejected.</p></section>\n"
#endif
    "</main>\n"
    "</body>\n"
    "</html>\n";

static const char EI_OPENAPI_JSON[] =
    "{"
    "\"openapi\":\"3.1.0\","
    "\"info\":{\"title\":\"embeddinggemma API\",\"version\":\"1.0.0\","
    "\"description\":\"Local EmbeddingGemma inference API.\"},"
    "\"servers\":[{\"url\":\"http://127.0.0.1:" EI_DOC_PORT "\"}],"
    "\"paths\":{"
    "\"/\":{\"get\":{\"summary\":\"Service discovery\",\"responses\":{"
    "\"200\":{\"description\":\"Service metadata\",\"content\":{"
    "\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Service\"}}}}}}},"
    "\"/docs\":{\"get\":{\"summary\":\"Human-readable API documentation\","
    "\"responses\":{\"200\":{\"description\":\"HTML documentation\"}}}},"
    "\"/openapi.json\":{\"get\":{\"summary\":\"OpenAPI document\","
    "\"responses\":{\"200\":{\"description\":\"OpenAPI 3.1 document\"}}}},"
    "\"/healthz\":{\"get\":{\"summary\":\"Readiness check\",\"responses\":{"
    "\"200\":{\"description\":\"Model is ready\",\"content\":{"
    "\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/Health\"}}}}}}},"
    "\"/api/tags\":{\"get\":{\"summary\":\"List served models\",\"responses\":{"
    "\"200\":{\"description\":\"Model list\",\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/TagsResponse\"}}}}}}},"
    "\"/api/embed\":{\"post\":{\"summary\":\"Create embeddings\","
    "\"requestBody\":{\"required\":true,\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/EmbedRequest\"}}}},"
    "\"responses\":{\"200\":{\"description\":\"Embedding vectors\",\"content\":{"
    "\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/EmbedResponse\"}}}},"
    "\"400\":{\"description\":\"Invalid request\",\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/Error\"}}}}}}},"
    "\"/v1/embeddings\":{\"post\":{\"summary\":\"Create OpenAI-compatible embeddings\","
    "\"requestBody\":{\"required\":true,\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/OpenAIEmbeddingRequest\"}}}},"
    "\"responses\":{\"200\":{\"description\":\"OpenAI embedding response\","
    "\"content\":{\"application/json\":{\"schema\":{\"$ref\":"
    "\"#/components/schemas/OpenAIEmbeddingResponse\"}}}},"
    "\"400\":{\"description\":\"Invalid request\",\"content\":{\"application/json\":{"
    "\"schema\":{\"$ref\":\"#/components/schemas/OpenAIError\"}}}}}}}},"
    "\"components\":{\"schemas\":{"
    "\"Service\":{\"type\":\"object\",\"required\":[\"name\",\"status\",\"docs\","
    "\"openapi\",\"health\",\"routes\"],\"properties\":{"
    "\"name\":{\"type\":\"string\"},\"status\":{\"type\":\"string\"},"
    "\"docs\":{\"type\":\"string\"},\"openapi\":{\"type\":\"string\"},"
    "\"health\":{\"type\":\"string\"},\"routes\":{\"type\":\"array\","
    "\"items\":{\"type\":\"string\"}}}},"
    "\"Health\":{\"type\":\"object\",\"required\":[\"status\"],\"properties\":{"
    "\"status\":{\"type\":\"string\",\"const\":\"ok\"}}},"
    "\"TagsResponse\":{\"type\":\"object\",\"required\":[\"models\"],\"properties\":{"
    "\"models\":{\"type\":\"array\",\"items\":{\"type\":\"object\","
    "\"required\":[\"name\"],\"properties\":{\"name\":{\"type\":\"string\"}}}}}},"
    "\"EmbedRequest\":{\"type\":\"object\",\"required\":[\"input\"],\"properties\":{"
    "\"model\":{\"type\":\"string\"},\"input\":{\"oneOf\":[{\"type\":\"string\"},"
    "{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":1,"
    "\"maxItems\":32}"
#ifdef EI_GEMMA2
    ",{\"$ref\":\"#/components/schemas/MediaInput\"},{\"type\":\"array\","
    "\"items\":{\"$ref\":\"#/components/schemas/MediaInput\"},\"minItems\":1,\"maxItems\":32}"
#endif
    "]},\"dimensions\":{\"type\":\"integer\","
    "\"enum\":[768,512,256,128],\"default\":768},\"encoding_format\":{"
    "\"type\":\"string\",\"enum\":[\"float\",\"base64\"],\"default\":\"float\"}}},"
#ifdef EI_GEMMA2
    "\"MediaInput\":{\"type\":\"object\",\"required\":[\"content\"],\"properties\":{"
    "\"content\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":64,\"items\":{\"oneOf\":["
    "{\"type\":\"object\",\"required\":[\"type\",\"text\"],\"properties\":{"
    "\"type\":{\"const\":\"text\"},\"text\":{\"type\":\"string\"}}},"
    "{\"type\":\"object\",\"required\":[\"type\",\"data\"],\"properties\":{"
    "\"type\":{\"enum\":[\"image\",\"audio\",\"video\"]},\"data\":{\"type\":\"string\","
    "\"description\":\"Base64 media bytes or a base64 data URL\"},"
    "\"fps\":{\"type\":\"number\",\"exclusiveMinimum\":0,\"maximum\":30,\"default\":1}}}]}}}},"
#endif
    "\"EmbedResponse\":{\"type\":\"object\",\"required\":[\"embeddings\"],"
    "\"properties\":{\"embeddings\":{\"type\":\"array\",\"items\":{\"oneOf\":[{"
    "\"type\":\"array\",\"items\":{\"type\":\"number\",\"format\":\"float\"}},{"
    "\"type\":\"string\",\"contentEncoding\":\"base64\"}]}}}},"
    "\"OpenAIEmbeddingRequest\":{\"allOf\":[{\"$ref\":"
    "\"#/components/schemas/EmbedRequest\"},{\"type\":\"object\","
    "\"required\":[\"model\"]}]},"
    "\"OpenAIEmbeddingResponse\":{\"type\":\"object\","
    "\"required\":[\"object\",\"data\",\"model\",\"usage\"],\"properties\":{"
    "\"object\":{\"type\":\"string\",\"const\":\"list\"},"
    "\"data\":{\"type\":\"array\",\"items\":{\"type\":\"object\","
    "\"required\":[\"object\",\"embedding\",\"index\"],\"properties\":{"
    "\"object\":{\"type\":\"string\",\"const\":\"embedding\"},"
    "\"embedding\":{\"oneOf\":[{\"type\":\"array\",\"items\":{"
    "\"type\":\"number\",\"format\":\"float\"}},{\"type\":\"string\","
    "\"contentEncoding\":\"base64\"}]},\"index\":{\"type\":\"integer\"}}}},"
    "\"model\":{\"type\":\"string\"},\"usage\":{\"type\":\"object\","
    "\"required\":[\"prompt_tokens\",\"total_tokens\"],\"properties\":{"
    "\"prompt_tokens\":{\"type\":\"integer\"},\"total_tokens\":{"
    "\"type\":\"integer\"}}}}},"
    "\"Error\":{\"type\":\"object\",\"required\":[\"error\"],\"properties\":{"
    "\"error\":{\"type\":\"string\"}}},"
    "\"OpenAIError\":{\"type\":\"object\",\"required\":[\"error\"],"
    "\"properties\":{\"error\":{\"type\":\"object\","
    "\"required\":[\"message\",\"type\",\"param\",\"code\"],\"properties\":{"
    "\"message\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"},"
    "\"param\":{\"type\":[\"string\",\"null\"]},"
    "\"code\":{\"type\":[\"string\",\"null\"]}}}}}"
    "}}"
    "}\n";

#endif
